### PR TITLE
Update composer.json and travis configs

### PR DESCRIPTION
**Pull request by dnsl48**
https://github.com/silverstripe/cwp-recipe-kitchen-sink/issues/46

### CODE REVIEW

**Comment by Cheddam** [comment]
@dnsl48 Looks like the PGSQL build is failing - perhaps a recent change to the PostgreSQL module broke something? Worth confirming before we merge this.

**Comment by dnsl48** [comment]
Well, the build is using the latest stable postgres driver. I think it might be worth having the broken build. Otherwise, I'm not sure the last pg builds (which ran 4 months ago) are gonna be green if we rerun them now.

**Comment by dnsl48** [comment]
Follow up issue - https://github.com/symbiote/silverstripe-multivaluefield/issues/64

**Comment by robbieaverill** [comment]
My suggestion would be to not add Travis changes that don't work and merge anyway, but include them in your follow up PR

**Comment by Cheddam** [comment]
@robbieaverill Not quite sure what you mean - is it not better to get the tests running correctly and red, than to leave them only half running and green? It gives us accurate visibility of the state of the module, even if we can't address the failure immediately.

**Comment by robbieaverill** [comment]
Perhaps adding support for Postgres is a feature in some cases, if it were designed for MySQL originally. Up to you, but you could easily leave the builds green and add a new PR with also green builds - that would be my preference :)

**Comment by dnsl48** [comment]
ok, removing tests for the time being - https://github.com/symbiote/silverstripe-multivaluefield/pull/66
when pg works (fixed) we can get them back

**Comment by Cheddam** [comment]
PostgreSQL issue is at #67.

**Pull request merged**
